name: 🐞 使用问题反馈
description: 反馈使用 Gemini Pro Chat 时遇到的问题或疑似缺陷
labels: ['pending triage', 'use']
body:
  - type: markdown
    attributes:
      value: |
        ### 提交前请确认
        感谢抽出时间填写问题反馈！提交前请确认以下几点：

        ✅ 已在 GitHub Issues 中搜索，确认该问题尚未被报告。
  - type: input
    id: os
    attributes:
      label: 你使用的操作系统是？
      placeholder: Mac、Windows、Linux
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 你使用的浏览器是？
      placeholder: Chrome、Firefox、Safari
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: 问题描述
      description: 请清晰、简洁地说明遇到的问题。
      placeholder: 问题描述
    validations:
      required: true
  - type: textarea
    id: prompt
    attributes:
      label: 你输入了什么提示词？
      description: 如果问题与提示词有关，请填写此项。
  - type: textarea
    id: console-logs
    attributes:
      label: 控制台日志
      description: 请检查浏览器控制台，如有错误信息请填写。
  - type: checkboxes
    id: will-pr
    attributes:
      label: 参与贡献
      options:
        - label: 我愿意为此问题提交 Pull Request。
          required: false
